### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by annefou** [matteo-ronchetti/Pointillism#5]
Hi,

Is there any license for your project? I could not find anything about it. 
Thanks.

**Comment by matteo-ronchetti** [comment]
I've added the license (MIT license). If you use part of this code I will appreciate if you cite this repository

**Comment by annefou** [comment]
Sure. No worries, I'll always refer to your repository.  And let me know if you want me to add specific citation when using Pointillism. Thank you.
